version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "ozassa"
    assignees:
      - "ozassa"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "auto-merge"
    ignore:
      # Ignore updates to these packages
      - dependency-name: "eslint"
        versions: ["9.x"]
      - dependency-name: "typescript"
        versions: ["5.x"]
    
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "ozassa"
    assignees:
      - "ozassa"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "github-actions"
      - "auto-merge"
      
  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "ozassa"
    assignees:
      - "ozassa"
    commit-message:
      prefix: "docker"
      include: "scope"
    labels:
      - "docker"
      - "auto-merge"