version: '3.8'

services:
  # Frontend (Nginx + React)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: fastcomm-frontend
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.prod.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
    networks:
      - fastcomm-network

  # Backend (Node.js + Express)
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: fastcomm-backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - RESEND_API_KEY=${RESEND_API_KEY}
      - CORS_ORIGIN=https://www.fastcomm.com.br
    networks:
      - fastcomm-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Watchtower for automatic updates (optional)
  watchtower:
    image: containrrr/watchtower
    container_name: fastcomm-watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=3600
    networks:
      - fastcomm-network

networks:
  fastcomm-network:
    driver: bridge

volumes:
  ssl-certs:
    driver: local